const productCatalogue2026Data = [
  {
    "Product Name": "AUTODESK AUTOCAD",
    "Category": "CAD & PLM",
    "Sub Category": "CAD SOFTWARE",
    "Description": "AUTOCAD WS IS AN AUTODESK SERVICE THAT LETS YOU EDIT AND COLLABORATE ON DESIGN DATA OVER THE WEB."
  },
  {
    "Product Name": "MODERNIZR",
    "Category": "IT MANAGEMENT",
    "Sub Category": "OTHER IT MANAGEMENT SOFTWARE",
    "Description": "MODERNIZR IS A JAVASCRIPT LIBRARY WHICH IS DESIGNED TO DETECT HTML5 AND CSS3 FEATURES IN VARIOUS BROWSERS, WHICH LETS JAVASCRIPT AVOID USING UNIMPLEMENTED FEATURES OR USE A WORKAROUND SUCH AS A SHIM TO EMULATE THEM."
  },
  {
    "Product Name": "UNIX",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "OPERATING SYSTEM",
    "Description": "UNIX IS A FAMILY OF MULTITASKING, MULTIUSER COMPUTER OPERATING SYSTEMS THAT DERIVE FROM THE ORIGINAL AT&T UNIX, DEVELOPED IN THE 1970S AT THE BELL LABS RESEARCH CENTER."
  },
  {
    "Product Name": "FACEBOOK FOR WEBSITES",
    "Category": "COLLABORATION & PRODUCTIVITY",
    "Sub Category": "SOCIAL NETWORK",
    "Description": "ALLOWS A USER TO MAKE A WEBSITE MORE SOCIABLE AND CONNECTED WITH INTEGRATIONS FROM THE HUGELY POPULAR FACEBOOK WEBSITE."
  },
  {
    "Product Name": "MYSQL",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "DATABASE SOFTWARE",
    "Description": "MYSQL COMMUNITY SERVER (GPL) (CURRENT GENERALLY AVAILABLE RELEASE: 5.7.13) MYSQL COMMUNITY SERVER IS THE WORLD'S MOST POPULAR OPEN SOURCE DATABASE."
  },
  {
    "Product Name": "COMODO SSL",
    "Category": "SECURITY",
    "Sub Category": "SECURITY",
    "Description": "COMODO IS A LEADING GLOBAL PROVIDER OF DIGITAL SECURITY, IDENTITY AND TRUST ASSURANCE SERVICES THAT INCLUDE A COMPREHENSIVE PORTFOLIO OF HIGH-ASSURANCE DIGITAL CERTIFICATES AND MANAGED PKI SOLUTIONS, ECOMMERCE ACCELERATION, AUTHENTICATION (MULTI-FACTOR) AND NETWORK VULNERABILITY SCANNING SERVICES CERTIFIED FOR PCI COMPLIANCE REPORTING. COMODO SECURITY SOLUTIONS, WITH OVER 85,000,000 ENDPOINT INSTALLATIONS OF ITS THREAT PREVENTION PRODUCTS, OFFERS AN EXTENSIVE SUITE OF SECURITY SOFTWARE AND SUPPORT SERVICES FOR BUSINESSES AND CONSUMERS ALIKE. CONTINUAL INNOVATION, A CORE COMPETENCE IN PKI AND A COMMITMENT TO REVERSING THE GROWTH OF INTERNET-CRIME DISTINGUISH THE COMODO COMPANIES AS VITAL PLAYERS IN THE INTERNET'S ONGOING DEVELOPMENT. WITH OFFICES IN THE US, UK, CHINA, INDIA, ROMANIA AND THE UKRAINE, COMODO SECURES AND AUTHENTICATES THE ONLINE TRANSACTIONS AND COMMUNICATIONS FOR OVER 750,000 BUSINESS CUSTOMERS AND MILLIONS OF CONSUMERS. PRODUCT WEBSITES: SSL - HTTPS://WWW.INSTANTSSL.COM/ SSL CERTIFICATE - HTTPS://SSL.COMODO.COM/ ANTIVIRUS - HTTPS://ANTIVIRUS.COMODO.COM/ FIREWALL - HTTPS://PERSONALFIREWALL.COMODO.COM/ COMODO ONE - HTTPS://ONE.COMODO.COM/ CWATCH - HTTPS://CWATCH.COMODO.COM/ ADVANCED ENDPOINT PROTECTION - HTTPS://ENTERPRISE.COMODO.COM SOCIAL MEDIA: BLOG - HTTPS://BLOG.COMODO.COM/ FORUM HTTPS://FORUMS.COMODO.COM/ FACEBOOK - HTTPS://WWW.FACEBOOK.COM/COMODOHOME TWITTER - HTTPS://TWITTER.COM/COMODODESKTOP GOOGLE PLUS HTTPS://PLUS.GOOGLE.COM/+COMODO/ YOUTUBE - HTTPS://WWW.YOUTUBE.COM/USER/COMODODESKTOP CONTACT US: TEL : +1.888.256.2608 / +1.703.637.9361 EMAIL:SALES@COMODO.COM"
  },
  {
    "Product Name": "JQUERY UI",
    "Category": "DEVELOPMENT",
    "Sub Category": "WEB FRAMEWORKS SOFTWARE",
    "Description": "JQUERY UI PROVIDES ABSTRACTIONS FOR LOW-LEVEL INTERACTION AND ANIMATION, ADVANCED EFFECTS AND HIGH-LEVEL, THEMEABLE WIDGETS, BUILT ON TOP OF THE JQUERY JAVASCRIPT LIBRARY, THAT YOU CAN USE TO BUILD HIGHLY INTERACTIVE WEB APPLICATIONS."
  },
  {
    "Product Name": "GOOGLE HOSTED JQUERY",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "INFRASTRUCTURE AS A SERVICE (IAAS) PROVIDERS",
    "Description": "JQUERY HOTED AT GOOGLE."
  },
  {
    "Product Name": "MICROSOFT SQL SERVER MANAGEMENT STUDIO",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "DATA INTEGRATION SOFTWARE",
    "Description": "SQL SERVER MANAGEMENT STUDIO (SSMS) IS A SOFTWARE APPLICATION FIRST LAUNCHED WITH THE MICROSOFT SQL SERVER 2005 THAT IS USED FOR CONFIGURING, MANAGING,"
  },
  {
    "Product Name": "FACEBOOK-SDK",
    "Category": "DEVELOPMENT",
    "Sub Category": "APPLICATION DEVELOPMENT SOFTWARE",
    "Description": "FOUNDED IN 2004, MISSION IS TO GIVE PEOPLE THE POWER TO BUILD COMMUNITY AND BRING THE WORLD CLOSER TOGETHER. PEOPLE USE FACEBOOK TO STAY CONNECTED WITH FRIENDS AND FAMILY, TO DISCOVER GOING ON IN THE WORLD, AND TO SHARE AND EXPRESS WHAT MATTERS TO THEM. FACEBOOK IS DEFINED BY OUR UNIQUE CULTURE ONE THAT REWARDS IMPACT. WE ENCOURAGE PEOPLE TO BE BOLD AND SOLVE THE PROBLEMS THEY CARE MOST ABOUT. WE WORK IN SMALL TEAMS AND MOVE FAST TO DEVELOP NEW PRODUCTS, CONSTANTLY ITERATING. THE PHRASE JOURNEY IS 1% REMINDS US THAT ONLY BEGUN TO FULFILL OUR MISSION TO BRING THE WORLD CLOSER TOGETHER."
  },
  {
    "Product Name": "MICROSOFT.NET",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "OPERATING SYSTEM",
    "Description": "MICROSOFT .NET FRAMEWORK 4 REDISTRIBUTABLE PACKAGE INSTALLS THE .NET FRAMEWORK RUNTIME AND ASSOCIATED FILES THAT ARE REQUIRED TO RUN AND"
  },
  {
    "Product Name": "PYTHON",
    "Category": "DEVELOPMENT",
    "Sub Category": "PYTHON PACKAGE SOFTWARE",
    "Description": "PYTHON IS A WIDELY USED GENERAL-PURPOSE, HIGH-LEVEL PROGRAMMING LANGUAGE. ITS DESIGN PHILOSOPHY EMPHASIZES CODE READABILITY AND ITS SYNTAX ALLOWS PROGRAMMERS TO EXPRESS CONCEPTS IN FEWER LINES OF CODE THAN WOULD BE POSSIBLE IN LANGUAGES SUCH AS C++ OR JAVA."
  },
  {
    "Product Name": "DEVICE WIDTH",
    "Category": "DEVELOPMENT",
    "Sub Category": "WEB TECHNOLOGY",
    "Description": "MOZILLA (STYLIZED AS MOZ://A) IS A FREE-SOFTWARE COMMUNITY CREATED IN 1998 BY MEMBERS OF NETSCAPE. THE MOZILLA COMMUNITY USES, DEVELOPS, SPREADS AND SUPPORTS MOZILLA PRODUCTS, THEREBY PROMOTING EXCLUSIVELY FREE SOFTWARE AND OPEN STANDARDS, WITH ONLY MINOR EXCEPTIONS.[1] THE COMMUNITY IS SUPPORTED INSTITUTIONALLY BY THE MOZILLA FOUNDATION AND ITS TAX-PAYING SUBSIDIARY, THE MOZILLA CORPORATION"
  },
  {
    "Product Name": "DRUPAL",
    "Category": "CONTENT MANAGEMENT",
    "Sub Category": "WEB CONTENT MANAGEMENT SOFTWARE",
    "Description": "DRUPAL IS AN OPEN SOURCE CONTENT MANAGEMENT PLATFORM POWERING MILLIONS OF WEBSITES AND APPLICATIONS"
  },
  {
    "Product Name": "GODADDY DNS",
    "Category": "DEVELOPMENT",
    "Sub Category": "MEDIA ONLINE",
    "Description": "DNS SERVICES PROVIDED BY GODADDY."
  },
  {
    "Product Name": "APPLE MOBILE WEB CLIPS ICON",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "OPERATING SYSTEMS",
    "Description": "SIMPLE AFFILIATE LINKS FOR YOUR WEBSITE OR BLOG. WITH ONE SNIPPET OF CODE ADDED TO YOUR WEBSITE, ALL ITUNES, APP STORE, IBOOKSTORE AND MAC APP STORE LINKS WILL BE CONVERTED TO AFFILIATE LINKS. ADD THE JAVASCRIPT TO THE FOOTER OF YOUR WEBSITE TO GET STARTED. LEARN MORE. AFFILIATE TOKEN. JAVASCRIPT CODE"
  },
  {
    "Product Name": "MICROSOFT SQL SERVER",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "DATABASE SOFTWARE",
    "Description": "SQL SERVER IS THE FOUNDATION OF MICROSOFT'S DATA PLATFORM, DELIVERING MISSION-CRITICAL PERFORMANCE WITH IN-MEMORY TECHNOLOGIES AND FASTER"
  },
  {
    "Product Name": "TWEMOJI",
    "Category": "E-COMMERCE",
    "Sub Category": "COMMERCE",
    "Description": "TWITTER EMOJI FOR EVERYONE"
  },
  {
    "Product Name": "MICROSOFT EXCHANGE",
    "Category": "OFFICE",
    "Sub Category": "CALENDAR SOFTWARE",
    "Description": "EXCHANGE 5.0 BROUGHT ANOTHER IMPORTANT TECHNICAL ADDITION THE INTRODUCTION OF A WEB-BASED E-MAIL CLIENT CALLED EXCHANGE WEB ACCESS (EWA)"
  },
  {
    "Product Name": "GOOGLE WEBMASTER",
    "Category": "DEVELOPMENT",
    "Sub Category": "SAAS",
    "Description": "WEBMASTER TOOLS PROVIDE YOU WITH A FREE AND EASY WAY TO MAKE YOUR SITE MORE GOOGLE-FRIENDLY."
  },
  {
    "Product Name": "JAVASCRIPT",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "DATABASE MANAGEMENT SYSTEMS",
    "Description": "JAVASCRIPT IS A SCRIPTING LANGUAGE MOST OFTEN USED FOR CLIENT-SIDE WEB DEVELOPMENT. ITS PROPER NAME IS ECMASCRIPT, THOUGH \"JAVASCRIPT\" IS MUCH MORE COMMONLY USED. THE WEBSITE USES JAVASCRIPT."
  },
  {
    "Product Name": "SALESFORCE.COM",
    "Category": "CRM & RELATED",
    "Sub Category": "SALES SOFTWARE",
    "Description": "CRM SOLUTION TAKES SALES FORCE AUTOMATION TO NEW HEIGHTS, WITH AN ARRAY OF CLOUD-BASED TOOLS THAT GIVES THEIR TEAM THE POWER TO SCORE MORE WINS, INCREASE PRODUCTIVITY, AND KEEP THE PIPELINE FILLED WITH SOLID LEADS."
  },
  {
    "Product Name": "ORIENTATION",
    "Category": "DEVELOPMENT",
    "Sub Category": "OTHER DEVELOPMENT SOFTWARE",
    "Description": "CSS ORIENTATION MEDIA QUERY."
  },
  {
    "Product Name": "FACEBOOK LIKE",
    "Category": "CRM & RELATED",
    "Sub Category": "SOCIAL MEDIA MARKETING",
    "Description": "ALLOWS USERS TO LIKE ITEMS THEY FIND ON THE WEB, SIMILAR TO HOW YOU LIKE ITEMS WITHIN FACEBOOK."
  },
  {
    "Product Name": "LETSENCRYPT",
    "Category": "SECURITY",
    "Sub Category": "SECURITY",
    "Description": "ENCRYPT IS A FREE OPEN CERTIFICATE AUTHORITY. SSL BY DEFAULT"
  },
  {
    "Product Name": "SSL BY DEFAULT",
    "Category": "PROFESSIONAL SERVICES",
    "Sub Category": "DIGITAL CERTIFICATE",
    "Description": "SSL BY DEFAULT IS AN INITIATIVE TO MAKE THE INTERNET MORE SECURE. WEBSITES AROUND THE WORLD ARE JOINING THEIR EFFORTS TO IMPLEMENT SSL BY DEFAULT."
  },
  {
    "Product Name": "ADOBE DREAMWEAVER",
    "Category": "OFFICE",
    "Sub Category": "AUTHORING AND PUBLISHING SOFTWARE",
    "Description": "ADOBE DREAMWEAVER IS A PROPRIETARY WEB DEVELOPMENT TOOL DEVELOPED BY ADOBE SYSTEMS."
  },
  {
    "Product Name": "MOBILE NON SCALEABLE CONTENT",
    "Category": "DEVELOPMENT",
    "Sub Category": "APPLICATION DEVELOPMENT SOFTWARE",
    "Description": "THIS CONTENT IS FORMATTED FOR MOBILE DEVICES, IT DOES NOT ALLOW THE CONTENT TO BE SCALED."
  },
  {
    "Product Name": "QUICKBOOKS",
    "Category": "ERP",
    "Sub Category": "ACCOUNTING & FINANCE SOFTWARE",
    "Description": "QUICKBOOKS IS INTUIT INC'S SET OF SOFTWARE SOLUTIONS DESIGNED TO MANAGE PAYROLL, INVENTORY, SALES AND OTHER NEEDS OF A SMALL BUSINESS. THE SOFTWARE'S FEATURES INCLUDE MARKETING TOOLS, MERCHANT SERVICES, PRODUCT AND SUPPLIES, TRAINING SOLUTIONS"
  },
  {
    "Product Name": "QUICKBOOKS DESKTOP",
    "Category": "ERP",
    "Sub Category": "ACCOUNTING & FINANCE SOFTWARE",
    "Description": "QUICKBOOKS PREMIER MAKES IT EASY TO TRACK INVENTORY, MONITOR EXPENSES AND GENERATE INVOICES. IT ALSO OFFERS INDUSTRY SPECIFIC FEATURES."
  }
];

module.exports = productCatalogue2026Data;
