const productCatalogueData = [
  {
    "Product Name": "AMAZON AWS",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "CLOUD PLATFORM AS A SERVICE (PAAS) SOFTWARE",
    "Description": "AMAZON WEB SERVICES (AWS) IS A COLLECTION OF REMOTE COMPUTING SERVICES, ALSO CALLED WEB SERVICES, THAT MAKE UP A CLOUD COMPUTING PLATFORM OFFERED BY AMAZON.COM."
  },
  {
    "Product Name": "GOOGLE",
    "Category": "CONTENT MANAGEMENT",
    "Sub Category": "WEB CONTENT MANAGEMENT SOFTWARE",
    "Description": "SITE HOSTED ON GOOGLE INFRASTRUCTURE."
  },
  {
    "Product Name": "MICROSOFT OFFICE",
    "Category": "OFFICE",
    "Sub Category": "AUTHORING AND PUBLISHING SOFTWARE",
    "Description": "MICROSOFT OFFICE IS AN OFFICE SUITE OF APPLICATIONS, SERVERS, AND SERVICES DEVELOPED BY MICROSOFT."
  },
  {
    "Product Name": "PHP",
    "Category": "DEVELOPMENT",
    "Sub Category": "WEB FRAMEWORKS SOFTWARE",
    "Description": "IS A SERVER-SIDE SCRIPTING LANGUAGE DESIGNED FOR WEB DEVELOPMENT BUT ALSO USED AS A GENERAL-PURPOSE PROGRAMMING LANGUAGE."
  },
  {
    "Product Name": "WORDPRESS",
    "Category": "CONTENT MANAGEMENT",
    "Sub Category": "WEB CONTENT MANAGEMENT SOFTWARE",
    "Description": "WORDPRESS IS WEB PUBLISHING SOFTWARE YOU CAN USE TO CREATE A BEAUTIFUL WEBSITE OR BLOG. WE LIKE TO SAY THAT WORDPRESS IS BOTH FREE AND PRICELESS AT THE SAME TIME."
  },
  {
    "Product Name": "UBUNTU",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "OPERATING SYSTEM",
    "Description": "UBUNTU IS AN OPEN SOURCE SOFTWARE OPERATING SYSTEM THAT RUNS FROM THE DESKTOP, TO THE CLOUD, TO ALL YOUR INTERNET CONNECTED THINGS."
  },
  {
    "Product Name": "BAIDU",
    "Category": "E-COMMERCE",
    "Sub Category": "E-COMMERCE PLATFORMS SOFTWARE",
    "Description": "BAIDU WAS FOUNDED IN 2000 BY INTERNET PIONEER ROBIN LI, CREATOR OF VISIONARY SEARCH TECHNOLOGY HYPERLINK ANALYSIS, WITH THE MISSION OF PROVIDING PEOPLE WITH THE BEST WAY TO FIND INFORMATION AND CONNECT USERS WITH SERVICES. OVER THE PAST DECADE WE HAVE STRIVED TO FULFILL THIS MISSION BY LISTENING CAREFULLY TO OUR NEEDS AND WANTS. TO PROVIDE INTELLIGENT, RELEVANT SEARCH RESULTS FOR THE TENS OF BILLIONS OF QUERIES THAT ARE ENTERED INTO OUR SEARCH PLATFORM EVERY DAY, WE FOCUS ON POWERING THE BEST TECHNOLOGY OPTIMIZED FOR UP-TO-DATE LOCAL TASTES AND PREFERENCES. OUR DEEP UNDERSTANDING OF CHINESE LANGUAGE AND CULTURE IS CENTRAL TO OUR SUCCESS AND THIS KIND OF KNOWLEDGE ALLOWS US TO TAILOR OUR SEARCH TECHNOLOGY FOR OUR NEEDS. WE PROVIDE OUR USERS WITH MANY CHANNELS TO FIND AND SHARE INFORMATION. IN ADDITION TO OUR CORE WEB SEARCH PRODUCT, WE POWER MANY POPULAR COMMUNITY-BASED PRODUCTS, SUCH AS BAIDU POSTBAR, THE FIRST AND LARGEST CHINESE-LANGUAGE QUERY-BASED SEARCHABLE ONLINE COMMUNITY PLATFORM, BAIDU KNOWS, THE LARGEST CHINESE-LANGUAGE INTERACTIVE KNOWLEDGE-SHARING PLATFORM, AND BAIDU ENCYCLOPEDIA, THE LARGEST USER-GENERATED CHINESE-LANGUAGE ENCYCLOPEDIA, TO NAME BUT A FEW. BEYOND THESE MARQUEE PRODUCTS WE ALSO OFFER DOZENS OF HELPFUL VERTICAL SEARCH-BASED PRODUCTS, SUCH AS MAPS, IMAGE SEARCH, VIDEO SEARCH, NEWS SEARCH, AND MANY MORE. WE POWER THESE THROUGH OUR CUTTING-EDGE TECHNOLOGY, CONTINUALLY INNOVATING TO ENHANCE THESE SERVICES. OUR NEW BOX COMPUTING OPEN PLATFORM BRINGS USERS DEEP-LINKED CONTENT AND EVEN APPLICATIONS THEY CAN USE DIRECTLY THROUGH THEIR SEARCH BOX. BAIDU CONTINUES TO INNOVATE TO MEET INTERNET INCREASINGLY DIVERSE TASTES. WITH OUR GOAL OF BEST SERVING THE NEEDS OF OUR USERS AND CUSTOMERS WITH INTELLIGENT AND RELEVANT SOLUTIONS, WE LOOK FORWARD TO A ROBUST FUTURE."
  },
  {
    "Product Name": "MICROSOFT WORD",
    "Category": "OFFICE",
    "Sub Category": "AUTHORING AND PUBLISHING SOFTWARE",
    "Description": "AT MICROSOFT, OUR MISSION IS TO EMPOWER EVERY PERSON AND EVERY ORGANIZATION ON THE PLANET TO ACHIEVE MORE. OUR MISSION IS GROUNDED IN BOTH THE WORLD IN WHICH WE LIVE AND THE FUTURE WE STRIVE TO CREATE. TODAY, WE LIVE IN A MOBILE-FIRST, CLOUD-FIRST WORLD, AND THE TRANSFORMATION WE ARE DRIVING ACROSS OUR BUSINESSES IS DESIGNED TO ENABLE MICROSOFT AND OUR CUSTOMERS TO THRIVE IN THIS WORLD."
  },
  {
    "Product Name": "MICROSOFT POWERPOINT",
    "Category": "OFFICE",
    "Sub Category": "PRESENTATION SOFTWARE",
    "Description": "MICROSOFT POWERPOINT IS A SLIDE SHOW PRESENTATION PROGRAM CURRENTLY DEVELOPED BY MICROSOFT. POWERPOINT INITIALLY NAMED \"PRESENTER"
  },
  {
    "Product Name": "NGINX",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "WEB ACCELERATOR SOFTWARE",
    "Description": "NGINX ACCELERATES CONTENT AND APPLICATION DELIVERY, IMPROVES SECURITY, FACILITATES AVAILABILITY AND SCALABILITY FOR THE BUSIEST WEB SITES ON THE INTERNET."
  },
  {
    "Product Name": "GOOGLE ANALYTICS",
    "Category": "CRM & RELATED",
    "Sub Category": "MARKETING SOFTWARE",
    "Description": "GOOGLE ANALYTICS NOT ONLY LETS YOU MEASURE SALES AND CONVERSIONS, BUT ALSO GIVES YOU FRESH INSIGHTS INTO HOW VISITORS USE YOUR SITE, HOW THEY ARRIVED ON YOUR SITE, AND HOW YOU CAN KEEP THEM COMING BACK. DELIVERED ON GOOGLE'S WORLD-CLASS PLATFORM."
  },
  {
    "Product Name": "JQUERY",
    "Category": "DEVELOPMENT",
    "Sub Category": "WEB FRAMEWORKS SOFTWARE",
    "Description": "JQUERY IS A FAST AND CONCISE JAVASCRIPT LIBRARY THAT SIMPLIFIES HTML DOCUMENT TRAVERSING, EVENT HANDLING, ANIMATING, AND AJAX INTERACTIONS FOR RAPID WEB DEVELOPMENT. JQUERY IS DESIGNED TO CHANGE THE WAY THAT YOU WRITE JAVASCRIPT. JQUERY WAS CREATED BY JOHN RESIG (HTTP://EJOHN.ORG) AND ANNOUNCED AT BARCAMPNYC ON JANUARY 14TH, 2006. SINCE THEN JQUERY HAS CHANGED THE INTERNET INDUSTRY AND THE WAY DEVELOPERS WRITE JAVASCRIPT. CURRENTLY JQUERY IS USED ON 20% OF ALL SITES ON THE INTERNET AND HAS AN EXTENSIVE ADOPTION RATE FROM COMPANIES LARGE AND SMALL."
  },
  {
    "Product Name": "LIGHTBOX",
    "Category": "DEVELOPMENT",
    "Sub Category": "WEB FRAMEWORKS SOFTWARE",
    "Description": "LIGHTBOX IS A FULL SERVICE DIGITAL AGENCY BASED IN DUBLIN, SPECIALISING IN THE DELIVERY OF RICH MEDIA CAMPAIGNS FOR OUR CLIENTS. WE DEVELOP COMPLEX WEB APPLICATIONS IN AREAS SUCH AS SOCIAL NETWORKING, ONLINE VIDEO AND ECOMMERCE. CLIENTS INCLUDE TOYOTA, WHOSEVIEW.COM, MEDIACONTACT.IE, INSTITUTE OF INTERNATIONAL AND EUROPEAN AFFAIRS AND WHERETOEAT.IE"
  },
  {
    "Product Name": "AMAZON",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "INFRASTRUCTURE AS A SERVICE (IAAS) PROVIDERS",
    "Description": "AMAZON STRIVES TO BE EARTH'S MOST CUSTOMER-CENTRIC COMPANY WHERE PEOPLE CAN FIND AND DISCOVER VIRTUALLY ANYTHING THEY WANT TO BUY ONLINE. BY GIVING CUSTOMERS MORE OF WHAT THEY WANT - LOW PRICES, VAST SELECTION, AND CONVENIENCE - AMAZON CONTINUES TO GROW AND EVOLVE AS A WORLD-CLASS E-COMMERCE PLATFORM. FOUNDED BY JEFF BEZOS, THE AMAZON.COM WEBSITE STARTED IN 1995 AS A PLACE TO BUY BOOKS BECAUSE OF THE UNIQUE CUSTOMER EXPERIENCE THE WEB COULD OFFER BOOK LOVERS. BEZOS BELIEVED THAT ONLY THE INTERNET COULD OFFER CUSTOMERS THE CONVENIENCE OF BROWSING A SELECTION OF MILLIONS OF BOOK TITLES IN A SINGLE SITTING. DURING THE FIRST 30 DAYS OF BUSINESS, AMAZON FULFILLED ORDERS FOR CUSTOMERS IN 50 STATES AND 45 COUNTRIES - ALL SHIPPED FROM HIS SEATTLE-AREA GARAGE. AMAZON'S EVOLUTION FROM WEB SITE TO E-COMMERCE PARTNER TO DEVELOPMENT PLATFORM IS DRIVEN BY THE SPIRIT OF INNOVATION THAT IS PART OF THE COMPANY'S DNA. THE WORLD'S BRIGHTEST TECHNOLOGY MINDS COME TO AMAZON.COM TO RESEARCH AND DEVELOP TECHNOLOGY THAT IMPROVES THE LIVES OF SHOPPERS AND SELLERS AROUND THE WORLD."
  },
  {
    "Product Name": "VIEWPORT META",
    "Category": "DEVELOPMENT",
    "Sub Category": "SOFTWARE",
    "Description": "THIS PAGE USES THE VIEWPORT META TAG WHICH MEANS THE CONTENT MAY BE OPTIMIZED FOR MOBILE CONTENT."
  },
  {
    "Product Name": "CENTOS",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "OPERATING SYSTEM",
    "Description": "CENTOS IS A LINUX DISTRIBUTION THAT PROVIDES A FREE, ENTERPRISE-CLASS, COMMUNITY-SUPPORTED COMPUTING PLATFORM FUNCTIONALLY COMPATIBLE WITH ITS UPSTREAM SOURCE, RED HAT ENTERPRISE LINUX."
  },
  {
    "Product Name": "GOOGLE API ANALYTICS",
    "Category": "OTHER ANALYTICS",
    "Sub Category": "SOFTWARE",
    "Description": "MISSION IS TO ORGANIZE THE INFORMATION AND MAKE IT UNIVERSALLY ACCESSIBLE AND USEFUL. SINCE OUR FOUNDING IN 1998, GOOGLE HAS GROWN BY LEAPS AND BOUNDS. FROM OFFERING SEARCH IN A SINGLE LANGUAGE WE NOW OFFER DOZENS OF PRODUCTS AND VARIOUS FORMS OF ADVERTISING AND WEB APPLICATIONS FOR ALL KINDS OF SCORES OF LANGUAGES. AND STARTING FROM TWO COMPUTER SCIENCE STUDENTS IN A UNIVERSITY DORM ROOM, WE NOW HAVE THOUSANDS OF EMPLOYEES AND OFFICES AROUND THE WORLD. A LOT HAS CHANGED SINCE THE FIRST GOOGLE SEARCH ENGINE APPEARED. BUT SOME THINGS CHANGED: OUR DEDICATION TO OUR USERS AND OUR BELIEF IN THE POSSIBILITIES OF THE INTERNET ITSELF."
  },
  {
    "Product Name": "DEBIAN",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "OPERATING SYSTEMS",
    "Description": "DEBIAN IS A UNIX-LIKE COMPUTER OPERATING SYSTEM THAT IS COMPOSED ENTIRELY OF FREE SOFTWARE AND PACKAGED BY A GROUP OF INDIVIDUALS PARTICIPATING IN THE DEBIAN PROJECT."
  },
  {
    "Product Name": "SPF",
    "Category": "CYBERSECURITY SERVICES",
    "Sub Category": "EMAIL SECURITY SERVICES PROVIDERS",
    "Description": "THE SENDER POLICY FRAMEWORK IS AN OPEN STANDARD SPECIFYING A TECHNICAL METHOD TO PREVENT SENDER ADDRESS FORGERY."
  },
  {
    "Product Name": "MAX WIDTH",
    "Category": "DIGITAL ADVERTISING",
    "Sub Category": "MPM",
    "Description": "MEDIA QUERY TO LIMIT CSS TO DISPLAY FOR DEVICES WITH A MAXIMUM WIDTH DEFINED."
  },
  {
    "Product Name": "GOOGLE APPS",
    "Category": "OFFICE",
    "Sub Category": "AUTHORING AND PUBLISHING SOFTWARE",
    "Description": "GOOGLE GIVES YOU THE POWER TO COLLABORATE, TRACK AND MANAGE"
  },
  {
    "Product Name": "GOOGLE CLOUD PLATFORM",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "DATABASE SOFTWARE",
    "Description": "GOOGLE CLOUD LETS YOU BUILD AND HOST APPLICATIONS AND WEBSITES, STORE DATA, AND ANALYZE DATA ON GOOGLE'S SCALABLE INFRASTRUCTURE."
  },
  {
    "Product Name": "GSTATIC",
    "Category": "GOOGLE STATIC CONTENT",
    "Sub Category": "CONTENT MANAGEMENT",
    "Description": "GOOGLE HAS OFF-LOADED STATIC CONTENT (JAVASCRIPT/IMAGES/CSS) TO A DIFFERENT DOMAIN NAME IN AN EFFORT TO REDUCE BANDWIDTH USAGE AND INCREASE NETWORK PERFORMANCE FOR THE END USER."
  },
  {
    "Product Name": "MICROSOFT AZURE",
    "Category": "IT INFRASTRUCTURE",
    "Sub Category": "INFRASTRUCTURE AS A SERVICE (IAAS) PROVIDERS",
    "Description": "AT MICROSOFT, OUR MISSION IS TO EMPOWER EVERY PERSON AND EVERY ORGANIZATION ON THE PLANET TO ACHIEVE MORE. OUR MISSION IS GROUNDED IN BOTH THE WORLD IN WHICH WE LIVE AND THE FUTURE WE STRIVE TO CREATE. TODAY, WE LIVE IN A MOBILE-FIRST, CLOUD-FIRST WORLD, AND THE TRANSFORMATION WE ARE DRIVING ACROSS OUR BUSINESSES IS DESIGNED TO ENABLE MICROSOFT AND OUR CUSTOMERS TO THRIVE IN THIS WORLD."
  },
  {
    "Product Name": "AKAMAI DNS",
    "Category": "CYBERSECURITY SERVICES",
    "Sub Category": "VULNERABILITY ASSESSMENT SERVICES PROV",
    "Description": "THE AKAMAI INTELLIGENT PLATFORM IS A DISTRIBUTED CLOUD COMPUTING PLATFORM THAT OPERATES WORLDWIDE. IT IS A NETWORK OF OVER 170,000 SERVERS[18] DEPLOYED IN MORE THAN 100[18] COUNTRIES. THESE SERVERS RESIDE IN MORE THAN 1,300[18] OF THE WORLD'S NETWORKS GATHERING REAL TIME INFORMATION ABOUT TRAFFIC, CONGESTION, AND TROUBLE SPOTS."
  },
  {
    "Product Name": "MIN WIDTH",
    "Category": "DEVELOPMENT",
    "Sub Category": "SOFTWARE",
    "Description": "A CSS MEDIA QUERY TO DISPLAY SPECIFIC CSS IF A DEVICE GREATER THAN THE MINIMUM WIDTH SPECIFIED."
  },
  {
    "Product Name": "IPHONE / MOBILE COMPATIBLE",
    "Category": "DIGITAL ADVERTISING",
    "Sub Category": "MEDIA",
    "Description": "MANAGE ALL OF ITS GLOBAL MEDIA RELATED ASSETS."
  },
  {
    "Product Name": "ASP.NET",
    "Category": "DEVELOPMENT",
    "Sub Category": "WEB FRAMEWORKS SOFTWARE",
    "Description": "ASP.NET IS AN OPEN-SOURCE[2] SERVER-SIDE WEB APPLICATION FRAMEWORK DESIGNED FOR WEB DEVELOPMENT TO PRODUCE DYNAMIC WEB PAGES. IT WAS DEVELOPED BY MICROSOFT TO ALLOW PROGRAMMERS TO BUILD DYNAMIC WEB SITES, WEB APPLICATIONS AND WEB SERVICES. IT WAS FIRST RELEASED IN JANUARY 2002 WITH VERSION 1.0 OF THE .NET FRAMEWORK, AND IS THE SUCCESSOR TO MICROSOFT'S ACTIVE SERVER PAGES (ASP) TECHNOLOGY. ASP.NET IS BUILT ON THE COMMON LANGUAGE RUNTIME (CLR), ALLOWING PROGRAMMERS TO WRITE ASP.NET CODE USING ANY SUPPORTED .NET LANGUAGE. THE ASP.NET SOAP EXTENSION FRAMEWORK ALLOWS ASP.NET COMPONENTS TO PROCESS SOAP MESSAGES. ASP.NET'S SUCCESSOR IS ASP.NET CORE. IT IS A RE-IMPLEMENTATION OF ASP.NET AS A MODULAR WEB FRAMEWORK, TOGETHER WITH OTHER FRAMEWORKS LIKE ENTITY FRAMEWORK. THE NEW FRAMEWORK USES THE NEW OPEN-SOURCE .NET COMPILER PLATFORM (CODENAME \"ROSLYN\") AND IS CROSS PLATFORM. ASP.NET MVC, ASP.NET WEB API, AND ASP.NET WEB PAGES (A PLATFORM USING ONLY RAZOR PAGES) HAVE MERGED INTO A UNIFIED MVC 6.[3]"
  },
  {
    "Product Name": "AKAMAI CONTENT DELIVERY NETWORK (CDN)",
    "Category": "HOSTING",
    "Sub Category": "CONTENT DELIVERY NETWORK (CDN) SOFTWARE",
    "Description": "AKAMAI TECHNOLOGIES, INC. IS A CONTENT DELIVERY NETWORK (CDN) AND CLOUD SERVICES PROVIDER HEADQUARTERED IN CAMBRIDGE, MASSACHUSETTS, IN THE UNITED STATES."
  },
  {
    "Product Name": "AJAX LIBRARIES API",
    "Category": "HOSTING",
    "Sub Category": "WEB CONTENT MANAGEMENT SOFTWARE",
    "Description": "THE AJAX LIBRARIES API IS A CONTENT DISTRIBUTION NETWORK AND LOADING ARCHITECTURE FOR THE MOST POPULAR, OPEN SOURCE JAVASCRIPT LIBRARIES."
  }
];

module.exports = productCatalogueData;
